---

- name: "{{ansible_distribution}}: delete spacewalk?"
  debug:
    msg: delete_spacewalk is set to True

# todo
#- name: "{{ansible_distribution}}: delete repo configuration"

- name: "{{ansible_distribution}}: stop spacewalk services"
  service:
    name:
      - spacewalk-wait-for-jabberd.service
      - spacewalk-wait-for-tomcat.service
    state: stopped

- name: "{{ansible_distribution}}: remove packages"
  yum:
    name:
      - postgresql
      - postgresql-libs
      - postgresql-jdbc
      - postgresql-contrib
      - postgresql-server
      - python2-spacewalk-certs-tools
      - python2-spacewalk-usix
      - spacewalk-admin
      - spacewalk-backend
      - spacewalk-backend-app
      - spacewalk-backend-applet
      - spacewalk-backend-config-files
      - spacewalk-backend-config-files-tool
      - spacewalk-backend-iss
      - spacewalk-backend-iss-export
      - spacewalk-backend-libs
      - spacewalk-backend-package-push-server
      - spacewalk-backend-server
      - spacewalk-backend-sql
      - spacewalk-backend-sql-postgresql
      - spacewalk-backend-tools
      - spacewalk-backend-xml-export-lib
      - spacewalk-backend-xmlrpc
      - spacewalk-base
      - spacewalk-base-minimal
      - spacewalk-base-minimal-config
      - spacewalk-branding
      - spacewalk-certs-tools
      - spacewalk-common
      - spacewalk-config
      - spacewalk-dobby
      - spacewalk-doc-indexes
      - spacewalk-html
      - spacewalk-setup-jabberd
      - spacewalk-java
      - spacewalk-java-config
      - spacewalk-java-lib
      - spacewalk-java-postgresql
      - spacewalk-postgresql
      - spacewalk-repo
      - spacewalk-schema
      - spacewalk-search
      - spacewalk-selinux
      - spacewalk-setup
      - spacewalk-setup-jabberd
      - spacewalk-setup-postgresql
      - spacewalk-taskomatic
      - spacewalk-usix
    state: absent

- name: "{{ansible_distribution}}: delete spacewalk config files and data"
  #shell: rm -Rf "{{item}}"
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - /var/www/cobbler
    - /var/www/html
    - /etc/httpd/conf.d/*spacewalk-server*
    - /var/lib/pgsql
    - /var/spacewalk
    - /usr/share/spacewalk

    #-rm -Rf /etc/pki/spacewalk/ /etc/selinux/targeted/active/modules/400/spacewalk/ /etc/systemd/system/multi-user.target.wants/spacewalk.target /etc/yum.repos.d/group_spacewalkproject-java-packages-epel-7.repo /etc/rhn/spacewalk-repo-sync/

- name: "{{ansible_distribution}}: kill java processes"
  shell: kill -9 $(ps -ef | grep -i spacewalk | grep -v grep | awk '{print $2}')

- name: "{{ansible_distribution}}: restart httpd"
  service:
    name: httpd
    state: restarted
