---

- name: "{{ ansible_distribution }}: install nginx"
  yum:
    name: nginx

- name: "{{ ansible_distribution }}: start and enable nginx"
  service:
    enabled: true
    name: nginx
    state: started
