---
- name: Detect OS family and run OS family specific tasks
  hosts: all

  tasks:

  - include: debian.yml
    when: ansible_os_family == 'Debian' or ansible_distribution == 'Ubuntu'

  - include: darwin.yml
    when: ansible_os_family == 'Darwin'

  - include: windows.yml
    when: ansible_os_family == 'Windows'

  - include: redhat.yml
    when: ansible_os_family == 'RedHat' or ansible_distribution == 'CentOS'

