---

- name: "{{ansible_distribution}}: install rpmfusion free"
  dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-28.noarch.rpm
    state: present
  when: ansible_distribution == 'Fedora'

- name: "{{ansible_distribution}}: install rpmfusion non-free"
  dnf:
    name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-28.noarch.rpm
    state: present
  when: ansible_distribution == 'Fedora'

#- name: "{{ansible_distribution}}: install rpmfusion-free-release-tainted"
#  dnf:
#    name: 

# consider this for the future
# sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
