---

- name: "{{ansible_distribution}}: install Apache"
  yum:
    name:
      - httpd
      - mod_ssl
    state: present
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'

- name: "{{ansible_distribution}}: start and enable apache service"
  service:
    enabled: yes
    name: httpd
    state: started
  when: ansible_os_family == 'RedHat'
