---

- name: "{{ ansible_distribution }}: Chapter 1.1. How to Build an LFS System"
  vars:
    msg: |
      Linux From Scratch - Version Latest Stable
      1.1. How to Build an LFS System
      http://www.linuxfromscratch.org/lfs/view/stable/chapter01/how.html
  debug:
    msg: "{{ msg.split('\n') }}"
