---

- name: "{{ ansible_distribution }}: Chapter 1. Introduction"
  vars:
    msg: |
      Linux From Scratch - Version Latest Stable
      Chapter 1. Introduction
      http://www.linuxfromscratch.org/lfs/view/stable/chapter01/chapter01.html
  debug:
    msg: "{{ msg.split('\n') }}"

- name: "{{ ansible_distribution }}: 1.1. How to Build an LFS System"
  include: how.yml

- name: "{{ ansible_distribution }}: 1.2. What's new since the last release"
  include: whatsnew.yml

- name: "{{ ansible_distribution }}: 1.3. Changelog"
  include: changelog.yml

- name: "{{ ansible_distribution }}: 1.4. Resources"
  include: resources.yml

- name: "{{ ansible_distribution }}: 1.5. Help"
  include: askforhelp.yml
