---

- name: "{{ ansible_distribution }}: Chapter 3.2. All Packages"
  vars:
    msg: |
      Linux From Scratch - Latest Stable
      Chapter 3.2. All Packages
      http://www.linuxfromscratch.org/lfs/view/stable/chapter03/packages.html
  debug:
    msg: "{{ msg.split('\n') }}"

#- name: "{{ansible_distribution}}: install the package-list file"
#  copy:
#    content: |
#      acl-2.2.53.tar.gz
#      attr-2.4.48.tar.gz
#      autoconf-2.69.tar.xz
#      automake-1.16.1.tar.xz
#      bash-5.0.tar.gz
#      bc-1.07.1.tar.gz
#      binutils-2.32.tar.xz
#      bison-3.3.2.tar.xz
#      bzip2-1.0.6.tar.gz
#      check-0.12.0.tar.gz
#      coreutils-8.30.tar.xz
#      dbus-1.12.12.tar.gz
#      dejagnu-1.6.2.tar.gz
#      diffutils-3.7.tar.xz
#      e2fsprogs-1.44.5.tar.gz
#      elfutils-0.176.tar.bz2
#      eudev-3.2.7.tar.gz
#      expat-2.2.6.tar.bz2
#      expect5.45.4.tar.gz
#      file-5.36.tar.gz
#      findutils-4.6.0.tar.gz
#      flex-2.6.4.tar.gz
#      gawk-4.2.1.tar.xz
#      gcc-8.2.0.tar.xz
#      gdbm-1.18.1.tar.gz
#      gettext-0.19.8.1.tar.xz
#      glibc-2.29.tar.xz
#      gmp-6.1.2.tar.xz
#      gperf-3.1.tar.gz
#      grep-3.3.tar.xz
#      groff-1.22.4.tar.gz
#      grub-2.02.tar.xz
#      gzip-1.10.tar.xz
#      iana-etc-2.30.tar.bz2
#      inetutils-1.9.4.tar.xz
#      intltool-0.51.0.tar.gz
#      iproute2-4.20.0.tar.xz
#      kbd-2.0.4.tar.xz
#      kmod-26.tar.xz
#      less-530.tar.gz
#      lfs-bootscripts-20180820.tar.bz2
#      libcap-2.26.tar.xz
#      libffi-3.2.1.tar.gz
#      libpipeline-1.5.1.tar.gz
#      libtool-2.4.6.tar.xz
#      linux-4.20.12.tar.xz
#      m4-1.4.18.tar.xz
#      make-4.2.1.tar.bz2
#      man-db-2.8.5.tar.xz
#      man-pages-4.16.tar.xz
#      meson-0.49.2.tar.gz
#      mpc-1.1.0.tar.gz
#      mpfr-4.0.2.tar.xz
#      ninja-1.9.0.tar.gz
#      ncurses-6.1.tar.gz
#      openssl-1.1.1a.tar.gz
#      patch-2.7.6.tar.xz
#      perl-5.28.1.tar.xz
#      pkg-config-0.29.2.tar.gz
#      procps-ng-3.3.15.tar.xz
#      psmisc-23.2.tar.xz
#      Python-3.7.2.tar.xz
#      python-3.7.2-docs-html.tar.bz2
#      readline-8.0.tar.gz
#      sed-4.7.tar.xz
#      shadow-4.6.tar.xz
#      sysklogd-1.5.1.tar.gz
#      systemd-240.tar.gz
#      systemd-man-pages-240.tar.xz
#      sysvinit-2.93.tar.xz
#      tar-1.31.tar.xz
#      tcl8.6.9-src.tar.gz
#      texinfo-6.5.tar.xz
#      tzdata2018i.tar.gz
#      udev-lfs-20171102.tar.bz2
#      util-linux-2.33.1.tar.xz
#      vim-8.1.tar.bz2
#      XML-Parser-2.44.tar.gz
#      xz-5.2.4.tar.xz
#      zlib-1.2.11.tar.xz
#      bzip2-1.0.6-install_docs-1.patch
#      coreutils-8.30-i18n-1.patch
#      glibc-2.29-fhs-1.patch
#      kbd-2.0.4-backspace-1.patch
#      sysvinit-2.93-consolidated-1.patch
#      systemd-240-security_fixes-2.patch
#    dest: "{{lfs}}/package-list"
#
#- name: "{{ansible_distribution}}: get a list of the packages"
#  command: cat "{{lfs}}/package-list"
#  register: package_list
#
#- name: "{{ansible_distribution}}: show me the list of files"
#  debug: msg={{package_list.stdout_lines}}
