--- # http://www.linuxfromscratch.org/lfs/view/stable/chapter04/settingenvironment.html
## 4.4. Setting Up the Environment

- name: "{{ansible_distribution}}: configure the lfs user bash_profile"
  copy:
    content: |
      exec env -i HOME=$HOME TERM=$TERM PS1='\u:\w\$ ' /bin/bash
    dest: /home/lfs/.bash_profile
    group: lfs
    owner: lfs

- name: "{{ansible_distribution}}: configure the lfs user bashrc"
  copy:
    content: |
      set +h
      umask 022
      LFS={{lfs}}
      LC_ALL=POSIX
      LFS_TGT=$(uname -m)-lfs-linux-gnu
      PATH=/tools/bin:/bin:/usr/bin
      export LFS LC_ALL LFS_TGT PATH
    dest: /home/lfs/.bashrc
    group: lfs
    owner: lfs
