---

- name: Systemd daemon-reload
  systemd:
    daemon_reload: yes
  listen: systemd-daemon-reload

- name: Restart Docker service
  service:
    enabled: yes
    name: docker
    state: restarted
  listen: docker-restart
