---

- name: "{{ansible_distribution}}: install dependencies in distro repositories"
  dnf:
    name:
      - cmake
      - gcc-c++
      - gtk3
      - gtk3-devel
      - jansson
      - jansson-devel
      - libgcrypt
      - libgcrypt-devel
      - libzip
      - libzip-devel
      - zbar
      - zbar-devel
  when: ansible_distribution == 'Fedora'

- name: "{{ansible_distribution}}: clone git repos"
  git:
    clone: yes
    dest: /tmp
    repo:
      - https://github.com/paolostivanin/otpclient.git
      - https://github.com/paolostivanin/libcotp.git
      - https://github.com/paolostivanin/libbaseencode.git

# libbaseencode
# https://github.com/paolostivanin/libbaseencode
# Library written in C for encoding and decoding data using base32 or base64 according to RFC-4648
- name: "{{ansible_distribution}}: install libbaseencode"
 cd libbaseencode
 mkdir build && cd $_
 cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ../
 make
 sudo make install

# libcotp
# https://github.com/paolostivanin/libcotp
# C library that generates TOTP and HOTP according to RFC-6238
- name: "{{ansible_distribution}}: install libcotp"
 git clone https://github.com/paolostivanin/libcotp.git
 cd libcotp
 mkdir build && cd $_
 cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ../   # add -DBUILD_TESTING=ON if you want to compile also the tests
 make
 sudo make install

# OTPClient
# https://github.com/paolostivanin/OTPClient#requirements
# Highly secure and easy to use GTK+ software for two-factor authentication that supports both Time-based One-time Passwords (TOTP) and HMAC-Based One-Time Passwords (HOTP).
- name: "{{ansible_distribution}}: install OTPClient"
 git clone https://github.com/paolostivanin/otpclient OTPClient
 cd OTPClient
 mkdir build && cd $_
 cmake -DCMAKE_INSTALL_PREFIX=/usr ..
 make
 sudo make install
