---

- name: "{{ansible_distribution}}: install the mariadb repo file"
  copy:
    content: |
      # MariaDB {{galera_version}} CentOS repository list
      # http://downloads.mariadb.org/mariadb/repositories/
      [mariadb]
      name = MariaDB
      baseurl = http://yum.mariadb.org/{{galera_version}}/centos7-amd64
      gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
      gpgcheck=1
    dest: /etc/yum.repos.d/mariadb.repo
    owner: root
  when: ansible_os_family == 'RedHat'

- name: "{{ansible_distribution}}: install mariadb"
  yum:
    name:
      - MariaDB-client
      - MariaDB-server
    state: present
  when:
    - ansible_os_family == 'RedHat'
    - ansible_di

- name: "{{ansible_distribution}}: galera firewall rules"
  firewalld:
    immediate: yes
    permanent: true
    port: "{{item}}"
    state: enabled
    zone: public
  with_items:
    - 4444/tcp
    - 4567/tcp
    - 4568/tcp

- name: "{{ansible_distribution}}: mysql firewall rules"
  firewalld:
    immediate: yes
    permanent: true
    service: mysql
    state: enabled
    zone: public

- name: "{{ansible_distribution}}: make sure selinux dependencies are installed"
  yum:
    name:
      - libselinux-python
      - policycoreutils-python
    state: present
  when: ansible_os_family == 'RedHat'

- name: "{{ansible_distribution}}: configure selinux to allow galera ports"
  seport:
    ports: "{{item}}"
    proto: tcp
    reload: true
    setype: mysqld_port_t
    state: present
  when: ansible_os_family == 'RedHat'
  with_items:
    - 4567
    - 4568
    - 4444

- name: "{{ansible_distribution}}: grant selinux permissive for mysqld"
  selinux_permissive:
    name: mysqld_t
    permissive: true
  when: ansible_os_family == 'RedHat'
