---

- name: "{{ ansible_distribution }}: Remove old version of packer"
  file:
    dest: /usr/local/bin/packer.io
    state: absent

- name: "{{ansible_distribution}}: Download and unpack packer"
  unarchive:
    dest: /opt
    remote_src: yes
    src: https://releases.hashicorp.com/packer/{{ VERSION }}/packer_{{ VERSION }}_linux_amd64.zip

- name: "{{ansible_distribution}}: Create symlink to binary to fix conflict with name 'packer'"
  # cracklib also has a library named packer which creates a conflict with Hashicorp's packer
  file:
    dest: /usr/local/bin/packer.io
    src: /opt/packer
    state: link
