--- # https://docs.openstack.org/glance/queens/install/

- name: glance
  block:
    - name: create glance mysql database
      mysql_db:
        name: glance
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: create glance mysql user
      mysql_user:
        name: glance
        password: "{{ the_password }}"
        priv: 'glance.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: create auth fact
      set_fact:
        keystone_auth:
          # https://blog.oddbit.com/post/2015-10-26-ansible-20-new-openstack-modules/
          # https://github.com/ansible/ansible/issues/19621
          auth_url: http://controller0:5000/v3
          username: admin
          password: "{{ the_password }}"
          project_name: admin
          project_domain_name: Default
          user_domain_name: Default
      register: keystone_auth

    - name: create the glance user
      os_user:
        auth: "{{ keystone_auth }}"
        name: glance
        password: "{{ the_password }}"
        state: present
        domain: default
      register: create_glance_user
      environment:
        # https://github.com/ansible/ansible/issues/26092
        OS_IDENTITY_API_VERSION: 3

    - name: add the glance user to the service project with admin role
      os_user_role:
        auth: "{{ keystone_auth }}"
        user: glance
        role: admin
        project: service
      register: glance_to_service_with_admin
      environment:
        # https://github.com/ansible/ansible/issues/26092
        OS_IDENTITY_API_VERSION: 3

    - name: create the glance service
      os_keystone_service:
        auth: "{{ keystone_auth }}"
        description: "OpenStack Image Service"
        name: glance
        service_type: image
        state: present
      register: create_glance_service
      environment:
        # https://github.com/ansible/ansible/issues/26092
        OS_IDENTITY_API_VERSION: 3

    - name: create image service endpoints
      os_keystone_endpoint:
        auth: "{{ keystone_auth }}"
        endpoint_interface: "{{ item }}"
        region: RegionOne
        service: glance
        state: present
        url: http://controller0:9292
      register: create_image_endpoints
      with_items:
        - public
        - internal
        - admin
      environment:
        # https://github.com/ansible/ansible/issues/26092
        OS_IDENTITY_API_VERSION: 3

    - name: install glance
      yum:
        name: openstack-glance

    - name: "{{ ansible_distribution }}: glance-api.conf"
      copy:
        content: |
          [database]
          connection = mysql+pymysql://glance:{{ the_password }}@controller/glance

          [keystone_authtoken]
          auth_uri = http://controller0:5000
          auth_url = http://controller0:5000
          memcached_servers = controller:11211
          auth_type = password
          project_domain_name = Default
          user_domain_name = Default
          project_name = service
          username = glance
          password = "{{ the_password }}"

          [paste_deploy]
          flavor = keystone

          [glance_store]
          stores = file,http
          default_store = file
          filesystem_store_datadir = /var/lib/glance/images/
        dest: /etc/glance/glance-api.conf
      notify: "restart glance-api"

    - name: "{{ ansible_distribution }}: glance-registry.conf"
      copy:
        content: |
          [database]
          connection = mysql+pymysql://glance:{{ the_password }}@controller0/glance

          [keystone_authtoken]
          auth_uri = http://controller0:5000
          auth_url = http://controller0:5000
          memcached_servers = controller0:11211
          auth_type = password
          project_domain_name = Default
          user_domain_name = Default
          project_name = service
          username = glance
          password = "{{ the_password }}"

          [paste_deploy]
          flavor = keystone
        dest: /etc/glance/glance-registry.conf
      notify: "restart glance-registry"

    - name: populate the glance database
      command: /bin/sh -c "keystone-manage db_sync" keystone
      register: populate_glance_db

    - name: start and enable the glance services
      service:
        enabled: yes
        name: "{{ item }}"
        state: started
      with_items:
        - openstack-glance-api.service
        - openstack-glance-registry.service

  when:
    - ( 'controller' in ansible_hostname )
    - ansible_facts['distribution'] == 'CentOS'
