--- # https://docs.openstack.org/neutron/queens/install/compute-install-rdo.html

- name: networking compute
  block:

    - name: "{{ ansible_distribution }}: install neutron packages"
      yum:
        name:
          - openstack-neutron-linuxbridge
          - ebtables
          - ipset

    - name: configure neutron
      copy:
        content: |
          [DEFAULT]
          transport_url = rabbit://openstack:{{ the_password }}@controller0
          auth_strategy = keystone

          [keystone_authtoken]
          auth_uri = http://controller0:5000
          auth_url = http://controller0:35357
          memcached_servers = controller0:11211
          auth_type = password
          project_domain_name = default
          user_domain_name = default
          project_name = service
          username = neutron
          password = "{{ the_password }}"

          [oslo_concurrency]
          lock_path = /var/lib/neutron/tmp
        dest: /etc/neutron/neutron.conf

    - include: networking_option2_compute.yml

    - name: configure nova
      blockinfile:
        block: |
          [neutron]
          url = http://controller0:9696
          auth_url = http://controller0:35357
          auth_type = password
          project_domain_name = default
          user_domain_name = default
          region_name = RegionOne
          project_name = service
          username = neutron
          password = "{{ the_password }}" 
        path: /etc/nova/nova.conf
      notify: "restart openstack-nova-compute"

    - name: "{{ ansible_distribution }}: start and enable neutron services"
      service:
        enabled: yes
        name: neutron-linuxbridge-agent.service
        state: started

  when:
    - ( 'compute' in ansible_hostname )
    - ansible_facts['distribution'] == 'CentOS'
