--- # https://docs.openstack.org/nova/queens/install/compute-install.html
# https://docs.openstack.org/nova/queens/install/compute-install-rdo.html

- name: "{{ ansible_distribution }}: install compute"
  yum:
    name: openstack-nova-compute

- name: "{{ ansible_distribution }}: compute configuration"

- name: "{{ ansible_distribution }}: compute services"
  service:
    enabled: yes
    name: "{{ item }}"
    state: started
  with_items:
    - libvirtd.service
    - openstack-nova-compute
