--- # https://docs.openstack.org/nova/queens/install/compute-install.html
# https://docs.openstack.org/nova/queens/install/compute-install-rdo.html
- name: nova compute
  block:

    - name: install compute
      yum:
        name: openstack-nova-compute

    - name: compute configuration
      copy:
        content: |
          [DEFAULT]
          enabled_apis = osapi_compute,metadata
          transport_url = rabbit://openstack:{{ the_password }}@controller0
          my_ip = "{{ ansible_default_ipv4.address }}"
          use_neutron = True
          firewall_driver = nova.virt.firewall.NoopFirewallDriver

          [api]
          auth_strategy = keystone

          [glance]
          api_servers = http://controller0:9292

          [oslo_concurrency]
          lock_path = /var/lib/nova/tmp

          [keystone_authtoken]
          auth_url = http://controller0:5000/v3
          memcached_servers = controller0:11211
          auth_type = password
          project_domain_name = default
          user_domain_name = default
          project_name = service
          username = nova
          password = "{{ the_password }}"

          [placement]
          os_region_name = RegionOne
          project_domain_name = Default
          project_name = service
          auth_type = password
          user_domain_name = Default
          auth_url = http://controller0:5000/v3
          username = placement
          password = "{{ the_password }}"

          [vnc]
          enabled = True
          server_listen = 0.0.0.0
          server_proxyclient_address = $my_ip
          novncproxy_base_url = http://controller0:6080/vnc_auto.html
        dest: /etc/nova/nova.conf

    - name: compute services
      service:
        enabled: yes
        name: "{{ item }}"
        state: started
      with_items:
        - libvirtd.service
        - openstack-nova-compute

  when:
    - ( 'compute' in ansible_hostname )
    - ansible_facts['distribution'] == 'CentOS'

- name: after compute has been configured, discover compute host
  shell: /bin/sh -c "nova-manage cell_v2 discover_hosts --verbose" nova
  register: discover_compute
  when:
    - ( 'controller' in ansible_hostname )
    - ansible_facts['distribution'] == 'CentOS'

- name: output discover_compute
  debug:
    msg: "{{ discover_compute }}"

# you could also add the following to nova.conf on the controller:
# [scheduler]
# discover_hosts_in_cells_interval = 300
