---

- name: mariadb service handler
  service:
    name: mariadb.service
    state: restarted
  listen: "restart mariadb"

- name: memcached service handler
  service:
    name: memcached.service
    state: restarted
  listen: "restart memcached"

- name: etcd service handler
  service:
    name: etcd.service
    state: restarted
  listen: "restart etcd"

- name: httpd service handler
  service:
    name: httpd.service
    state: restarted
  listen: "restart httpd"

- name: glance-api handler
  service:
    name: openstack-glance-api.service
    state: restarted
  listen: "restart glance-api"

- name: glance-registry handler
  service:
    name: openstack-glance-registry.service
    state: restarted
  listen: "restart glance-registry"
