--- # https://docs.openstack.org/neutron/queens/install/compute-install-rdo.html

- name: "{{ ansible_distribution }}: install neutron packages"
  yum:
    name:
      - openstack-neutron-linuxbridge
      - ebtables
      - ipset

## /etc/neutron/neutron.conf

[DEFAULT]
transport_url = rabbit://openstack:RABBIT_PASS@controller0
auth_strategy = keystone

[keystone_authtoken]
auth_uri = http://controller0:5000
auth_url = http://controller0:35357
memcached_servers = controller0:11211
auth_type = password
project_domain_name = default
user_domain_name = default
project_name = service
username = neutron
password = NEUTRON_PASS

[oslo_concurrency]
lock_path = /var/lib/neutron/tmp

## /etc/nova/nova.conf

url = http://controller:9696
auth_url = http://controller:35357
auth_type = password
project_domain_name = default
user_domain_name = default
region_name = RegionOne
project_name = service
username = neutron
password = NEUTRON_PASS

# this will be a handler
- name: "{{ ansible_distribution }}: restart openstack-nova-compute"
  service:
    name: openstack-nova-compute.service
    state: restarted

- name: "{{ ansible_distribution }}: start and enable neutron services"
  service:
    enabled: yes
    name: neutron-linuxbridge-agent.service
    state: started
