---

- name: "{{ ansible_distribution }}: uninstall packstack"
  include: uninstall.yml
  when: uninstall == "True"

- name: "{{ ansible_distribution }}: Configure server for Packstack"
  block:
    - name: "{{ ansible_distribution }}: disable firewalld, NetworkManager"
      service:
        enabled: no
        name: "{{ item }}"
        state: stopped
      with_items:
        - firewalld
        - NetworkManager

    - name: "{{ ansible_distribution }}: configure network"
      service:
        enabled: yes
        name: network
        state: started

- name: "{{ ansible_distribution }}: Install Packstack"
  block:
    - name: "{{ansible_distribution}}: install dependencies"
      yum:
        name:
          - python-zmq
        state: installed
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution != 'Fedora'

    - name: "{{ansible_distribution}}: install dependencies"
      dnf:
        name:
          - python-zmq
        state: installed
      when: ansible_distribution == 'Fedora'

    - name: "{{ansible_distribution}}: packstack release"
      yum:
        name: centos-release-openstack-{{ VERSION }}
        state: installed
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution != 'Fedora'

    - name: "{{ansible_distribution}}: install packstack"
      yum:
        name: openstack-packstack
        state: installed
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution != 'Fedora'

    - name: "{{ansible_distribution}}: run the standalone installer"
      shell: packstack --allinone

  when:
    - uninstall != 'True'
