---

- name: "{{ansible_distribution}}: delete packstack?"
  debug:
    msg: delete_packstack is set to True

# todo
#- name: "{{ansible_distribution}}: delete repo configuration"

- name: "{{ansible_distribution}}: destroy virtual machines"
  ignore_errors: True
  shell: for x in $(virsh list --all | grep instance- | awk '{print $2}') ; do virsh destroy $x ; virsh undefine $x ; done
  when:
    - uninstall == 'True'

- name: "{{ansible_distribution}}: stop and disable  services"
  ignore_errors: True
  service:
    enabled: no
    name: "{{item}}"
    state: stopped
  when:
    - uninstall == 'True'
  with_items:
    - epmd@0.0.0.0.service
    - epmd@0.0.0.0.socket
    - ovsdb-server.service
    - rabbitmq-server.service
    - redis.service

- name: "{{ansible_distribution}}: remove packages"
  ignore_errors: True
  yum:
    name:
      - "*cinder*"
      - "*glance*"
      - httpd
      - iscsi-initiator-utils
      - "*keystone*"
      - "*memcache*"
      - mysql
      - mysql-server
      - "*nagios*"
      - "*nova*"
      - nrpe
      - ntp
      - ntp-perl
      - ntpdate
      - "*openstack*"
      - openvswitch
      - perl-DBI
      - perl-DBD-MySQL
      - puppet
      - rabbitmq-server
      - scsi-target-utils
      - "*swift*"
    state: absent
  when:
    - uninstall == 'True'

- name: "{{ansible_distribution}}: kill processes"
  ignore_errors: True
  shell: ps -ef | grep -i repli | grep swift | awk '{print $2}' | xargs kill

- name: "{{ansible_distribution}}: delete data"
  ignore_errors: True
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - /etc/aodh
    - /etc/ceilometer
    - /etc/cinder
    - /etc/glance
    - /etc/gnocchi
    - /etc/keystone
    - /etc/nagios
    - /etc/neutron
    - /etc/nova
    - /etc/puppet
    - /etc/rabbitmq
    - /etc/redis*
    - /etc/rsync.d/frag*
    - /etc/swift
    - /etc/yum.repos.d/packstack_*
    - /root/.my.cnf
    - /srv/node/device*/*
    - /var/cache/swift
    - /var/lib/ceilometer
    - /var/lib/cinder/
    - /var/lib/glance
    - /var/lib/gnocchi
    - /var/lib/haproxy
    - /var/lib/hiera
    - /var/lib/mysql/
    - /var/lib/neutron
    - /var/lib/nova
    - /var/lib/puppet
    - /var/lib/redis
    - /var/log/aodh
    - /var/log/ceilometer
    - /var/log/cinder
    - /var/log/glance
    - /var/log/glusterfs
    - /var/log/gnocchi
    - /var/log/horizon
    - /var/log/keystone
    - /var/log/neutron
    - /var/log/nova
    - /var/log/openvswitch
    - /var/log/rabbitmq
    - /var/log/redis
  when:
    - uninstall == 'True'

- name: "{{ansible_distribution}}: umount /srv/node/device*"
  ignore_errors: True
  shell: umount /srv/node/device*
  when:
    - uninstall == 'True'

- name: "{{ansible_distribution}}: killall -9 dnsmasq tgtd httpd"
  ignore_errors: True
  shell: killall -9 dnsmasq tgtd httpd
  when:
    - uninstall == 'True'

- name: "{{ansible_distribution}}: setenforce 1"
  ignore_errors: True
  shell: setenforce 1
  when:
    - uninstall == 'True'

- name: "{{ansible_distribution}}: vgremove -f cinder-volumes"
  ignore_errors: True
  shell: vgremove -f cinder-volumes
  when:
    - uninstall == 'True'

- name: "{{ansible_distribution}}: losetup -a | sed -e 's/:.*//g' | xargs losetup -d"
  ignore_errors: True
  shell: losetup -a | sed -e 's/:.*//g' | xargs losetup -d
  when:
    - uninstall == 'True'

- name: "{{ansible_distribution}}: find /etc/pki/tls -name ssl_ps* | xargs rm -rf"
  ignore_errors: True
  shell: find /etc/pki/tls -name "ssl_ps*" | xargs rm -rf
  when:
    - uninstall == 'True'

- name: "{{ansible_distribution}}: for x in $(df | grep /lib/ | sed -e 's/.* //g') ; do umount $x; done"
  ignore_errors: True
  shell: for x in $(df | grep "/lib/" | sed -e 's/.* //g') ; do umount $x; done
  when:
    - uninstall == 'True'

- name: "{{ansible_distribution}}: remove apache configuration files"
  ignore_errors: True
  file:
    path: /etc/httpd/conf.d/"{{item}}"
    state: absent
  notify: restart-httpd
  with_items:
    - 00-nova-placement-api.conf
    - 10-aodh_wsgi.conf
    - 10-gnocchi_wsgi.conf
    - 10-keystone_wsgi_*
    - 15-default.conf
    - 15-horizon_vhost.conf
    - openstack-dashboard.conf
  when:
    - uninstall == 'True'
