---

- hosts: zk
  become: yes
  gather_facts: true

  handlers:

    - name: Restart systemd
      systemd:
        daemon_reload: yes
      listen: Restart systemd

  tasks:

    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Update /etc/hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item].ansible_hostname }}"
      with_items: "{{ groups.zk }}"

    - name: Firewall rules
      firewalld:
        immediate: yes
        permanent: true
        port: "{{item}}"
        state: enabled
        zone: public
      with_items:
        - 2888/tcp
        - 3888/tcp
        - 2181/tcp

    - name: Install OpenJDK
      yum:
        name:
        - java-1.8.0-openjdk
        - java-1.8.0-openjdk-headless

    - name: Download Zookeeper source
      get_url:
        dest: /tmp
        url: "{{ URL }}"

    - name: Unpack tar archive
      unarchive:
        dest: /opt
        src: /tmp/apache-zookeeper-{{ VERSION }}.tar.gz

    - name: Link binaries
      file:
        dest: /opt/zookeeper
        src: /opt/zookeeper-{{ VERSION }}

    - name: Create Zookeeper group
      group:
        name: zookeeper
        state: present

    - name: Create Zookeeper user
      user:
        comment: "Zookeeper user"
        create_home: no
        group: zookeeper
        home: /opt/zookeeper
        name: zookeeper
        shell: /sbin/nologin
        state: present

    - name: Create Zookeeper data directory
      file:
        dest: /opt/zookeeper/data
        state: directory

    - name: Change ownership to zookeeper
      file:
        dest: /opt/zookeeper
        group: zookeeper
        owner: zookeeper
        recurse: yes

    - name: Create Zookeeper config
      copy:
        content: |
          tickTime=2000
          initLimit=10
          syncLimit=5
          dataDir=/opt/zookeeper/data
          clientPort=2181
          server.1={{ hostvars[item]['ansible_default_ipv4']['address'] }}:2888:3888
          server.2={{ hostvars[item]['ansible_default_ipv4']['address'] }}:2888:3888
          server.3={{ hostvars[item]['ansible_default_ipv4']['address'] }}:2888:3888
        dest: /opt/zookeeper/conf/zoo.cfg

    - name: Create Zookeeper systemd service file
      copy:
        content: |
          [Unit]
          Description=Zookeeper Service

          [Service]
          Type=simple
          WorkingDirectory=/opt/zookeeper/
          PIDFile=/opt/zookeeper/data/zookeeper_server.pid
          SyslogIdentifier=zookeeper
          User=zookeeper
          Group=zookeeper
          ExecStart=/opt/zookeeper/bin/zkServer.sh start
          ExecStop=/opt/zookeeper/bin/zkServer.sh stop
          Restart=always
          TimeoutSec=20
          SuccessExitStatus=130 143
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/sytem/zookeeper.service
      notify: "Restart systemd"

    - name: Start and enable Zookeeper service
      service:
        enabled: yes
        name: zookeeper.service
        state: started


  vars:
    URL: https://www.apache.org/dyn/closer.lua/zookeeper/zookeeper-{{ VERSION}}/apache-zookeeper-{{ VERSION }}.tar.gz
    VERSION: 3.6.1

