---

- name: "{{ansible_distribution}}: install the gcloud repo file"
  copy:
    content: |
      [google-cloud-sdk]
      name=Google Cloud SDK
      baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
             https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    dest: /etc/yum.repos.d/gcloud.repo
    owner: root
  when: ansible_os_family == 'RedHat'

- name: "{{ansible_distribution}}: install gcloud"
  yum:
    name: google-cloud-sdk
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'

- name: "{{ansible_distribution}}: install gcloud"
  dnf:
    name: google-cloud-sdk
  when:
    - ansible_distribution == 'Fedora'
