---
- name: "{{ ansible_distribution }}: install fail2ban"
  dnf:
    name: fail2ban
    state: present
  when: ansible_distribution == 'Fedora'

- name: "{{ ansible_distribution }}: configure fail2ban"
  blockinfile:
    path: /etc/fail2ban/jail.d/00-firewalld.conf
    block: |
      [sshd]
      enabled = true
  when: ansible_distribution == 'Fedora'

- name: "{{ ansible_distribution }}: start and enable fail2ban"
  service:
    name: fail2ban
    enabled: yes
    state: restarted
  when: ansible_distribution == 'Fedora'

- name: "{{ ansible_distribution }}: install fail2ban"
  apt:
    name: fail2ban
    state: present
  when: ansible_distribution == 'Ubuntu'

#- name: "{{ ansible_distribution }}: configure fail2ban"
  #blockinfile:
    #path: /etc/fail2ban/jail.d/00-firewalld.conf
    #block: |
      #[sshd]
      #enabled = true

- name: "{{ ansible_distribution }}: start and enable fail2ban"
  service:
    name: fail2ban
    enabled: yes
    state: restarted
  when: ansible_distribution == 'Ubuntu'
