---
# https://kubernetes.io/docs/tasks/tools/install-minikube/

- name: "{{ ansible_distribution }}: Download Minikube binary"
  get_url:
    dest: /usr/local/bin/minikube
    mode: 0755
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
