---

- name: Install epel-release & remi-release-7
  yum:
    name:
      - epel-release
      - http://rpms.remirepo.net/enterprise/remi-release-7.rpm

- name: Enable remi-release-7
  command: yum-config-manager --enable remi-php72

#- name: Enable remi-release-7
  #yum_repository:
    #description: "Remi Release PHP7"
    #enabled: yes
    #name: remi-php7

- name: Install php72
  yum:
    name:
      - php72
      - php72-php-intl
      - php72-php-pdo
      - php72-php-mysqlnd
