---

- name: "{{ ansible_distribution }}: 2.2. Host System Requirements"
  vars:
    msg: |
      Linux From Scratch - Latest Stable
      2.2. Host System Requirements
      http://www.linuxfromscratch.org/lfs/view/stable/chapter02/hostreqs.html
  debug:
    msg: "{{ msg.split('\n') }}"

- name: "{{ ansible_distribution }}: 2.2. Host System Requirements"
  block:

    - name: "{{ ansible_distribution }}: install development tools"
      yum:
        name: "@Development Tools"

    - name: "{{ ansible_distribution }}: install extra required packages"
      yum:
        name:
          - python3
          - texinfo

    - name: "{{ ansible_distribution }}: make /usr/bin/yacc a symlink to /usr/bin/bison - delete /usr/bin/yacc"
      file:
        path: /usr/bin/yacc
        state: absent

    - name: "{{ ansible_distribution }}: make /usr/bin/yacc a symlink to /usr/bin/bison - create symlink"
      file:
        src: /usr/bin/bison
        dest: /usr/bin/yacc
        state: link

  when: ansible_os_family == 'RedHat'
