---

- name: "{{ ansible_distribution }}: 2.7. Mounting the New Partition"
  vars:
    msg: |
      Linux From Scratch - Latest Stable
      2.7. Mounting the New Partition
      http://www.linuxfromscratch.org/lfs/view/stable/chapter02/mounting.html
  debug:
    msg: "{{ msg.split('\n') }}"

- name: stuff
  debug:
    msg:
      - "{{ lfs }}"
      - "{{ device }}1"

- name: "{{ ansible_distribution }}: mount device on /mnt/lfs"
  #shell: mount -t xfs "{{ device }}1" "{{ lfs }}"
  mount:
    fstype: xfs
    name: "{{ lfs }}"
    src: "{{ device }}1"
    state: mounted
