---

- hosts: ansible_nodes
  become: yes

  tasks:
    - name: run the redhat tasks
      block:
        - name: install httpd
          yum:
            name: httpd

        - name: start and enable httpd
          service:
            name: httpd
            state: started
            enabled: true

        - name: create index.html
          file:
            path: /var/www/index.html
            state: touch

        - name: "{{ansible_distribution}} - {{ansible_hostname}}: change index.html file"
          lineinfile:
            path: /var/www/index.html
            line: "Did this work?"
          notify: restart-httpd

      tags: redhat
      when: ansible_os_family == 'RedHat'

    - name: run the debian tasks
      block:
        - name: install apache2
          apt:
            name: apache2

        - name: start and enable apache2
          service:
            name: apache2
            state: started
            enabled: true

        - name: create index.html
          file:
            path: /var/www/html/index.html
            state: touch

      tags: debian
      when: ansible_os_family == 'Debian'

  vars:
    http_port: 80
    http_dir: /var/html

  handlers:
    - name: restart-httpd
      service:
        name: httpd
        state: restarted
      listen: "restart-httpd"
      
    - name: restart-apache2
      service:
        name: apache2
        state: restarted
      listen: "restart-apache2"
