---

- hosts: ansible_nodes
  become: yes

  tasks:
    - name: install httpd
      yum:
        name: httpd
      notify: restart-httpd
      tags: redhat
      when: ansible_os_family == 'RedHat'

    - name: install httpd
      apt:
        name: apache2
      #notify: restart-apache2
      when: ansible_os_family == 'Debian'

    - name: start and enable httpd
      service:
        name: httpd
        state: started
        enabled: true
      tags: redhat
      when: ansible_os_family == 'RedHat'

    - name: start and enable httpd
      service:
        name: apache2
        state: started
        enabled: true
      when: ansible_os_family == 'Debian'
  
    - name: create index.html
      file:
        path: /var/www/index.html
        state: touch
      tags: redhat
      when: ansible_os_family == 'RedHat'

    - name: "{{ansible_distribution}} - {{ansible_hostname}}: change index.html file"
      lineinfile:
        path: /var/www/index.html
        line: "Did this work???"
      notify: restart-httpd
      tags: redhat
      when: ansible_os_family == 'RedHat'

    - name: create index.html
      file:
        path: /var/www/html/index.html
        state: touch
      when: ansible_os_family == 'Debian'

  vars:
    http_port: 80
    http_dir: /var/html

  handlers:
    - name: restart-httpd
      service:
        name: httpd
        state: restarted
      listen: "restart-httpd"
      
   #- name: restart-apache2
   #  service:
   #    name: apache2
   #    state: restarted
   #  listen: "restart-apache2"
